name: Clean Composer and Packages

on:
  push:
    branches:
      - develop-aws

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove Composer-related files
      run: |
        rm -rf vendor
        rm -f composer.json
        rm -f composer.lock

    - name: Clear Composer Cache
      run: |
        composer clear-cache || true
        rm -rf ~/.composer/cache

    - name: List Remaining Files
      run: |
        echo "Remaining files and directories:"
        ls -al
