name: Clean Composer and Packages

on:
  push:
    branches:
      - develop-aws

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove vendor directory
      run: |
        if [ -d "vendor" ]; then
          echo "Removing vendor directory"
          rm -rf vendor
        else
          echo "Vendor directory does not exist"
        fi

    - name: Remove Composer-related files
      run: |
        if [ -f "composer.json" ]; then
          echo "Removing composer.json file"
          rm composer.json
        else
          echo "composer.json file does not exist"
        fi
        if [ -f "composer.lock" ]; then
          echo "Removing composer.lock file"
          rm composer.lock
        else
          echo "composer.lock file does not exist"
        fi

    - name: List remaining files and directories
      run: |
        echo "Remaining files and directories:"
        ls -al
