name: Install Packages

on:
  push:
    branches:
      - develop-aws

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl

    - name: Clear Composer Cache
      run: composer clear-cache

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache/files
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Remove vendor and composer.lock
      run: |
        rm -rf vendor
        rm -f composer.lock

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Require AWS SDK for PHP
      run: composer require aws/aws-sdk-php

    - name: Dump Autoload
      run: composer dump-autoload

    - name: Show List File
      run: ls -la
