name: Add and Commit Test File

on:
  push:
    branches:
      - develop-aws  # Change this to your target branch if different

jobs:
  add-commit-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add test.js file
      run: |
        echo "console.log('Hello, World!');" > test.js

    - name: Commit and Push Changes
      run: |
        git config --global user.email "htetlinoo@qualymm.com"
        git config --global user.name "QMHLO"
        git add test.js
        git commit -m "Add test.js file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
