name: Check Vendor Directory

on:
  push:
    branches:
      - develop-aws

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List directory contents
      run: |
        echo "Checking for vendor directory..."
        if [ -d "vendor" ]; then
          echo "Vendor directory exists."
          ls -l vendor
        else
          echo "Vendor directory does not exist."
        fi
