name: Composer Setup and Lock Update

on:
  push:
    branches:
      - develop-aws

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Adjust to match the PHP version on your server

    - name: Install Composer dependencies and update composer.lock
      run: |
        composer update --ignore-platform-reqs
        echo "Composer update completed successfully"

    - name: List files in the directory
      run: |
        ls -a
        echo "Listed files successfully"

    - name: List vendor directory
      run: |
        ls -la vendor
        echo "Displayed vendor directory successfully"

    - name: Read composer.json
      run: |
        cat composer.json
        echo "Displayed composer.json successfully"

    