name: Composer Setup

on:
  push:
    branches:
      - develop-aws

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Remove composer.lock and vendor directory
      run: |
        rm -rf vendor composer.lock

    - name: Install Composer dependencies (ignore platform requirements)
      run: |
        composer install --ignore-platform-reqs
        composer require aws/aws-sdk-php --ignore-platform-reqs

    - name: Commit vendor folder
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "htetlinoo@qualymm.com"
        git config --global user.name "QMHLO"
        git add vendor
        git commit -m "Add vendor folder"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/QMHLO/gh-action.git
