name: Composer Setup

on:
  push:
    branches:
      - develop-aws

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Remove composer.lock and vendor directory
      run: |
        rm -rf vendor composer.lock

    - name: Clear Composer Cache
      run: |
        composer clear-cache

    - name: Install Composer dependencies (ignore platform requirements)
      run: |
        composer config platform.php 7.4
        composer install --ignore-platform-reqs

    - name: Verify Installation
      run: |
        composer show aws/aws-sdk-php


    - name: List Remaining Files
      run: |
        echo "Remaining files and directories:"
        ls -al
