name: Install Packages

on:
  push:
    branches:
      - develop-aws

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl
        ini-values: post_max_size=256M, upload_max_filesize=256M

    - name: Clear Composer Cache
      run: composer clear-cache

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache/files
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Remove vendor and composer.lock
      run: |
        rm -rf vendor
        rm -f composer.lock

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Find out why PHP 8.1 is required
      run: composer why php

    - name: Show List
      run: ls -la

    - name: Show List .lock
      run: cat composer.lock

    - name: Display vendor directory contents
      run: ls -la vendor/composer

    - name: Display platform_check.php
      run: cat vendor/composer/platform_check.php
