name: Composer Setup

on:
  push:
    branches:
      - develop-aws

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Check PHP version
      run: php -v

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Clear Composer Cache
      run: composer clear-cache

    - name: Remove composer.lock and vendor directory
      run: |
        rm -f composer.lock
        rm -rf vendor

    - name: Install Composer dependencies (ignore platform requirements)
      run: |
        composer install --ignore-platform-reqs
        composer require aws/aws-sdk-php --ignore-platform-reqs

    - name: Verify Installation
      run: |
        composer show aws/aws-sdk-php

        - name: Commit and Push Changes
        run: |
          git config --global user.email "htetlinoo@qualy.com"
          git config --global user.name "QMHLO"
          git add composer.lock
          git commit -m "Update composer.lock"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
