name: Delete Composer Files

on:
  push:
    branches:
      - develop-aws

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove vendor directory and composer.lock file
      run: |
        rm -rf vendor
        rm composer.lock
