name: Composer Setup and Lock Update

on:
  push:
    branches:
      - develop-aws

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Adjust to match the PHP version on your server

    - name: Install Composer dependencies and update composer.lock
      run: |
        composer update --ignore-platform-reqs

     - name: Commit composer.lock if updated
      run: |
        git config --global user.name "QMHLO"
        git config --global user.email "htetlinoo@qualymm.com"
        git add composer.lock
        git commit -m "Update composer.lock for PHP 7.4 compatibility" || echo "No changes to commit"
        git push origin develop-aws
